Repository S3-26/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#6 Add files via upload
  java.pdf
Labels: good first issue, hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#7 Create a
  a
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#9 Create fhkjsg
  fhkjsg
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#10 Create s
  s
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#11 Create j
  j
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#12 Create a1
  a1
Labels: hacktoberfest-accepted

#13 Create a3
  a3
Labels: hacktoberfest-accepted

#14 Create a5
  a5
  d7
Labels: hacktoberfest-accepted

#15 Create f7
  bv
  f7
Labels: hacktoberfest-accepted

#16 Create d6
  d6
Labels: hacktoberfest-accepted

#17 Create mmt1
  mmt1
Labels: hacktoberfest-accepted

#18 Create mmt2
  mmt2
Labels: hacktoberfest2022, hacktoberfest-accepted

#19 Create mmt3
  mmt3
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#20 Create mmt4
  mmt4
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#21 Create ad
  ad
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#22 Create sd
  sd
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#24 kjh
  jk
  lk
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#25 Create df
  df
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted
